name = "minionu-api"
main = "src/index.js"
compatibility_date = "2026-10-07"
keep_vars = true

[[d1_databases]]
binding = "DB"
database_name = "minionu"
database_id = "b4f01eb9-00f3-451b-b470-2755f703bdfd"
migrations_dir = "migrations"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomLiveUpdates"

[[durable_objects.bindings]]
name = "DASHBOARD"
class_name = "GlobalDashboard"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomLiveUpdates"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["GlobalDashboard"]

[vars]
ALLOWED_ORIGINS = "https://galaobiel4.github.io,http://localhost:5500,http://127.0.0.1:5500"

