// Generated by npm run build:codepen. Configure API_BASE below before using the backend.
(async () => {
const pais = document.getElementById('pais');
const votacao = document.getElementById('votacao');

// Mantém a lista e o formulário simples do CodePen original.
function selecao(aba) {
  const listapaises = ['Brasil', 'Rússia', 'EUA', 'Índia', 'China', 'Nigéria', 'Alemanha', 'França', 'Turquia', 'Reino Unido'];
  pais.replaceChildren();
  votacao.replaceChildren();
  for (const [i, country] of listapaises.slice(0, aba === 'UNICEF' ? 10 : 9).entries()) {
    const detail = document.createElement('details');
    const summary = document.createElement('summary');
    const name = document.createElement('b');
    name.textContent = country;
    summary.append(name);
    const commentLabel = document.createElement('label');
    commentLabel.className = 'labelComentarios';
    commentLabel.htmlFor = `comentario-${i}`;
    commentLabel.textContent = 'Comentários:';
    const comment = document.createElement('textarea');
    comment.id = commentLabel.htmlFor;
    comment.className = 'comentarios';
    comment.maxLength = 4000;
    comment.placeholder = 'Insira comentários sobre a delegação...';
    detail.append(summary, commentLabel, document.createElement('br'), comment);
    pais.append(detail);
    const countryLabel = document.createElement('span');
    countryLabel.className = 'votopais';
    countryLabel.textContent = country;
    votacao.append(countryLabel);
    for (const [vote, label] of [['favoravel', 'Favorável'], ['abstido', 'Abstido'], ['contra', 'Contra']]) {
      const input = document.createElement('input');
      input.type = 'radio';
      input.name = `${country}voto`;
      input.value = vote;
      input.id = `voto-${i}-${vote}`;
      const text = document.createElement('label');
      text.htmlFor = input.id;
      text.textContent = label;
      votacao.append(input, text);
    }
    votacao.append(document.createElement('br'));
  }
}

window.selecao = selecao;
// Configure after deploying the Cloudflare Worker. Use http://localhost:8787 for local development.
const API_BASE = '';

const COUNTRIES = ['Brasil', 'Rússia', 'EUA', 'Índia', 'China', 'Nigéria', 'Alemanha', 'França', 'Turquia', 'Reino Unido'];
const COMMITTEES = [
  { code: 'CDH', name: 'Comissão de Direitos Humanos', countries: 9 },
  { code: 'OMS', name: 'Organização Mundial da Saúde', countries: 9 },
  { code: 'UNESCO', name: 'Organização das Nações Unidas para Educação, Ciência e Cultura', countries: 9 },
  { code: 'ONUM', name: 'ONU Mulheres', countries: 9 },
  { code: 'CSNU', name: 'Conselho de Segurança das Nações Unidas', countries: 9 },
  { code: 'ACNUR', name: 'Alto Comissariado das Nações Unidas para Refugiados', countries: 9 },
  { code: 'CDESC', name: 'Direitos econômicos, sociais e culturais da ONU', countries: 9 },
  { code: 'UNICEF', name: 'Fundo das Nações Unidas para a Infância', countries: 10 }
];
const committeeByCode = code => COMMITTEES.find(c => c.code === code);

// Criteria from the original CodePen. The roster is intentionally preserved.
const originalRules = {
  CSNU: { veto: true, paisesVeto: ['EUA', 'RUSSIA', 'CHINA', 'FRANCA', 'REINO UNIDO'], maioria: '3/5' },
  CDH: { veto: false, paisesVeto: [], maioria: 'simples' },
  OMS: { veto: false, paisesVeto: [], maioria: '2/3' },
  UNESCO: { veto: false, paisesVeto: [], maioria: '2/3' },
  ONUM: { veto: false, paisesVeto: [], maioria: 'simples' },
  UNICEF: { veto: false, paisesVeto: [], maioria: 'simples' },
  CDESC: { veto: false, paisesVeto: [], maioria: 'simples' },
  ACNUR: { veto: false, paisesVeto: [], maioria: 'simples' }
};
const countryKey = country => country.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase();
const VOTING_RULES = Object.freeze(Object.fromEntries(Object.entries(originalRules).map(([code, rule]) => {
  const vetoCountries = COUNTRIES.slice(0, committeeByCode(code).countries).filter(country => rule.paisesVeto.includes(countryKey(country)));
  return [code, Object.freeze({ ...rule, paisesVeto: Object.freeze(rule.paisesVeto), hasVeto: rule.veto, vetoCountries: Object.freeze(vetoCountries), majority: rule.maioria })];
})));

function emptyForm(code) {
  const committee = committeeByCode(code);
  const rule = VOTING_RULES[code];
  return { committee: code, hasVeto: rule.hasVeto, crisisTitle: '', crisisDetails: '', proposalText: '', votingRound: 0, state: { vetoCountries: [...rule.vetoCountries], delegations: COUNTRIES.slice(0, committee.countries).map(country => ({ country, comment: '', vote: '' })) } };
}



function calculateVote(code, delegations = []) {
  const rule = VOTING_RULES[code], committee = committeeByCode(code);
  if (!rule || !committee) throw new Error('Comitê inválido.');
  const counts = { favoravel: 0, contra: 0, abstido: 0, pending: 0 }, vetoedBy = [];
  for (const country of COUNTRIES.slice(0, committee.countries)) {
    const votes = delegations.filter(delegation => delegation?.country === country);
    const vote = votes.length === 1 ? votes[0].vote : '';
    if (['favoravel', 'contra', 'abstido'].includes(vote)) counts[vote]++;
    else counts.pending++;
    if (vote === 'contra' && rule.vetoCountries.includes(country)) vetoedBy.push(country);
  }
  const validVotes = counts.favoravel + counts.contra;
  const [numerator, denominator] = rule.majority.split('/').map(Number);
  const requiredVotes = rule.majority === 'simples' ? Math.floor(validVotes / 2) + 1 : Math.max(1, Math.ceil(validVotes * numerator / denominator));
  const status = counts.pending ? 'pending' : vetoedBy.length ? 'vetoed' : validVotes > 0 && counts.favoravel >= requiredVotes ? 'approved' : 'denied';
  return { status, counts, requiredVotes, validVotes, vetoedBy, majority: rule.majority };
}

const apiUrl = path => { if (!API_BASE) throw new Error('O site ainda precisa ser publicado com a URL do servidor.'); return `${API_BASE.replace(/\/$/, '')}${path}`; };
async function call(path, method = 'GET', body, token) {
  const headers = { 'content-type': 'application/json' }; if (token) headers.Authorization = `Bearer ${token}`;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 20000);
  try {
    const response = await fetch(apiUrl(path), { method, headers, signal: controller.signal, body: body === undefined ? undefined : JSON.stringify(body) });
    let data;
    try { data = await response.json(); } catch { throw new Error('O servidor não enviou uma resposta válida. Tente novamente.'); }
    if (!response.ok) { const error = new Error(data.error || 'Falha ao conectar.'); error.status = response.status; error.snapshot = data.snapshot; throw error; }
    return data;
  } catch (error) {
    if (error.name === 'AbortError') throw new Error('O servidor demorou para responder. Tente novamente.');
    throw error;
  } finally { clearTimeout(timeout); }
}
const login = (username, password) => call('/api/auth/login', 'POST', { username, password });
const loadDashboard = token => call('/api/dashboard', 'GET', undefined, token);
const loadForm = code => call(`/api/committees/${encodeURIComponent(code)}`);
const saveForm = (code, form) => call(`/api/committees/${encodeURIComponent(code)}`, 'PUT', form);
const finalizeProposal = (code, form, requestId) => call(`/api/committees/${encodeURIComponent(code)}/proposals`, 'POST', { ...form, requestId });
function watch(path, token, onUpdate, onStatus) {
  let socket, timer, stopped = false, attempt = 0;
  function connect() {
    if (stopped) return; onStatus('connecting');
    try { const url = new URL(apiUrl(path)); url.protocol = url.protocol === 'https:' ? 'wss:' : 'ws:'; socket = token ? new WebSocket(url, ['mun-live', `mun-auth.${token}`]) : new WebSocket(url); }
    catch (error) { onStatus('error', error.message); return; }
    socket.addEventListener('open', () => { attempt = 0; onStatus('connected'); });
    socket.addEventListener('message', event => { try { onUpdate(JSON.parse(event.data)); } catch {} });
    socket.addEventListener('close', event => {
      if (stopped) return;
      if (event.code === 1008 && token) { stopped = true; onStatus('expired'); return; }
      onStatus('reconnecting'); timer = setTimeout(connect, Math.min(1000 * 2 ** attempt++, 15000));
    });
    socket.addEventListener('error', () => onStatus('error', 'Sem conexão. Tentando reconectar…'));
  }
  connect(); return () => { stopped = true; clearTimeout(timer); socket?.close(); };
}
const watchDashboard = (token, onUpdate, onStatus = () => {}) => watch('/api/dashboard/live', token, onUpdate, onStatus);
const watchForm = (code, onUpdate, onStatus = () => {}) => watch(`/api/committees/${encodeURIComponent(code)}/live`, null, onUpdate, onStatus);
function createAutosave(code, onStatus = () => {}) {
  let pending, timer, inFlight, stopped = false;
  function flush() {
    timer = undefined; if (stopped || inFlight || !pending) return;
    const snapshot = pending; pending = undefined; onStatus('saving');
    let failed = false, retry = true;
    inFlight = saveForm(code, snapshot).then(saved => {
      if (!stopped && !pending) onStatus('saved', undefined, saved);
    }).catch(error => {
      if (stopped) return;
      if (error.status === 409) {
        stopped = true; pending = undefined;
        onStatus('conflict', error.message, error.snapshot);
        return;
      }
      failed = true; pending ||= snapshot;
      retry = !error.status || error.status >= 500 || error.status === 429;
      onStatus(retry ? 'error' : 'rejected', error.message);
    }).finally(() => {
      inFlight = undefined;
      if (!stopped && pending && retry) timer = setTimeout(flush, failed ? 2000 : 0);
    });
  }
  const enqueue = snapshot => { if (stopped) return; pending = snapshot; onStatus('pending'); if (!timer && !inFlight) timer = setTimeout(flush, 150); };
  // Wait for a PUT already sent before posting a completed voting round.
  enqueue.stop = () => { stopped = true; clearTimeout(timer); pending = undefined; return inFlight || Promise.resolve(); };
  enqueue.hasPending = () => Boolean(pending || inFlight);
  return enqueue;
}


const $ = id => document.getElementById(id);
const VETO = { brasil: 'Brasil', india: 'Índia', eua: 'EUA', turquia: 'Turquia', russia: 'Rússia', china: 'China', nigeria: 'Nigéria', alemanha: 'Alemanha', franca: 'França', uk: 'Reino Unido' };
const RESULTS = { approved: 'APROVADA', denied: 'NEGADA', vetoed: 'VETADA', pending: 'Aguardando votos' };
const VOTES = { favoravel: 'Favorável', contra: 'Contra', abstido: 'Abstido', '': 'Sem voto' };
let activeCode, autosave, stopWatch, loading = false, generation = 0, lastRevision = -1;
let votingRound = 0, proposals = [], historyLoaded = false, submission = null, finalizing = false;
const status = (message, state = '') => { $('sync-status').textContent = message; $('sync-status').dataset.status = state; };
const votingMessage = (message, state = '') => { $('voting-message').textContent = message; $('voting-message').dataset.status = state; };
const draftKey = code => `minionu-draft.${code}`;
const recoveredKey = code => `minionu-recovered.${code}`;
const node = (tag, text, className) => { const element = document.createElement(tag); if (text !== undefined) element.textContent = text; if (className) element.className = className; return element; };
function readStorage(key) { try { return JSON.parse(localStorage.getItem(key) || 'null'); } catch { return null; } }
function writeStorage(key, value) {
  try { if (value === null) localStorage.removeItem(key); else localStorage.setItem(key, JSON.stringify(value)); }
  catch { status('O navegador não permite guardar um rascunho local. Mantenha esta página aberta até salvar.', 'error'); }
}
function read() {
  const rule = VOTING_RULES[activeCode];
  return {
    committee: activeCode, hasVeto: rule.hasVeto, votingRound, proposalText: $('proposal-text').value,
    crisisTitle: document.querySelector('.crise').value, crisisDetails: document.querySelector('.detalhamentocrise').value,
    state: {
      vetoCountries: [...rule.vetoCountries],
      delegations: [...document.querySelectorAll('#pais details')].map(detail => {
        const country = detail.querySelector('summary').textContent.trim();
        return { country, comment: detail.querySelector('.comentarios').value, vote: [...document.querySelectorAll('#votacao input:checked')].find(input => input.name === `${country}voto`)?.value || '' };
      })
    }
  };
}
function persist(form = read()) { writeStorage(draftKey(activeCode), { form, baseRevision: lastRevision, submission }); }
function lockFields() {
  const locked = loading || finalizing || Boolean(submission);
  $('comite').disabled = locked || Boolean(autosave?.hasPending());
  document.querySelectorAll('.crise,.detalhamentocrise,.comentarios,#proposal-text,#votacao input').forEach(input => { input.disabled = locked; });
  document.querySelectorAll('#veto,#sem-veto,.paises-veto input').forEach(input => { input.disabled = true; });
  renderVote();
}
function renderVote() {
  if (!activeCode) return;
  const rule = VOTING_RULES[activeCode], result = calculateVote(activeCode, read().state.delegations);
  const majority = rule.majority === 'simples' ? 'Maioria simples: mais da metade' : `Maioria de ${rule.majority}`;
  $('voting-rule').textContent = `${majority} dos votos válidos. Abstenções não entram no cálculo; todas as delegações devem votar.${rule.hasVeto ? ` Voto contrário de ${rule.vetoCountries.join(', ')} veta a proposta.` : ' Este comitê não possui veto.'}`;
  $('vote-tally').textContent = `Favoráveis: ${result.counts.favoravel} · Contra: ${result.counts.contra} · Abstenções: ${result.counts.abstido} · Sem voto: ${result.counts.pending}`;
  $('vote-preview').textContent = result.counts.pending
    ? `Faltam ${result.counts.pending} voto(s) para concluir. Com a contagem atual: ${result.requiredVotes} voto(s) favorável(is) necessário(s).`
    : `Resultado: ${RESULTS[result.status]}. ${result.requiredVotes} voto(s) favorável(is) necessário(s) entre ${result.validVotes} voto(s) válido(s).${result.vetoedBy.length ? ` Veto de: ${result.vetoedBy.join(', ')}.` : ''}${!result.validVotes ? ' Sem votos válidos, a proposta não é aprovada.' : ''}`;
  $('finish-voting').textContent = finalizing ? 'Registrando votação…' : submission ? 'Verificar e concluir votação' : 'Concluir votação';
  $('finish-voting').disabled = loading || finalizing || (!submission && (!read().proposalText.trim() || result.counts.pending > 0));
}
function renderHistory() {
  $('proposal-log').replaceChildren();
  if (!proposals.length) {
    $('proposal-log').append(node('p', historyLoaded ? 'Nenhuma proposta concluída neste comitê.' : 'O histórico será carregado quando houver conexão.'));
    return;
  }
  for (const proposal of proposals) {
    const article = node('article');
    article.append(node('h3', `${RESULTS[proposal.status] || proposal.status} · Proposta ${proposal.votingRound + 1}`));
    const time = node('time', new Date(proposal.createdAt).toLocaleString('pt-BR'));
    time.dateTime = proposal.createdAt;
    article.append(time, node('p', proposal.proposalText, 'proposal-text'));
    if (proposal.crisisTitle) article.append(node('p', `Crise: ${proposal.crisisTitle}`));
    if (proposal.crisisDetails) {
      const crisis = node('details'); crisis.append(node('summary', 'Detalhamento da crise'), node('p', proposal.crisisDetails, 'proposal-text')); article.append(crisis);
    }
    article.append(node('p', `Favoráveis: ${proposal.counts.favoravel} · Contra: ${proposal.counts.contra} · Abstenções: ${proposal.counts.abstido}. Regra: ${proposal.majority === 'simples' ? 'maioria simples' : proposal.majority}. Necessários: ${proposal.requiredVotes} de ${proposal.validVotes} votos válidos.`));
    if (proposal.vetoedBy.length) article.append(node('p', `Veto de: ${proposal.vetoedBy.join(', ')}.`));
    const details = node('details'), table = node('table'), head = node('thead'), labels = node('tr');
    details.append(node('summary', 'Votos e comentários registrados'));
    for (const title of ['Delegação', 'Voto', 'Comentário']) labels.append(node('th', title));
    head.append(labels); table.append(head);
    const body = node('tbody');
    for (const delegation of proposal.delegations) {
      const row = node('tr'); row.append(node('td', delegation.country), node('td', VOTES[delegation.vote] || delegation.vote), node('td', delegation.comment || '—')); body.append(row);
    }
    table.append(body); const scroll = node('div', undefined, 'log-table'); scroll.append(table); details.append(scroll); article.append(details);
    $('proposal-log').append(article);
  }
}
function acceptHistory(form) {
  if (Array.isArray(form.proposals)) { proposals = form.proposals; historyLoaded = true; renderHistory(); }
  lastRevision = Math.max(lastRevision, form.revision ?? -1);
}
function restore(form) {
  $('comite').value = form.committee;
  window.selecao(form.committee);
  votingRound = form.votingRound ?? 0;
  const rule = VOTING_RULES[form.committee];
  $('veto').checked = rule.hasVeto; $('sem-veto').checked = !rule.hasVeto;
  document.querySelector('.crise').value = form.crisisTitle || '';
  document.querySelector('.detalhamentocrise').value = form.crisisDetails || '';
  document.querySelector('.crise').maxLength = 500; document.querySelector('.detalhamentocrise').maxLength = 5000;
  $('proposal-text').value = form.proposalText || '';
  for (const [id, country] of Object.entries(VETO)) $(id).checked = rule.vetoCountries.includes(country);
  for (const detail of document.querySelectorAll('#pais details')) {
    const country = detail.querySelector('summary').textContent.trim(), delegation = form.state.delegations.find(item => item.country === country);
    detail.querySelector('textarea').value = delegation?.comment || '';
    for (const input of document.querySelectorAll('#votacao input')) if (input.name === `${country}voto`) input.checked = input.value === delegation?.vote;
  }
  for (const id of ['proposal-panel', 'voting-controls', 'proposal-history']) $(id).hidden = false;
  lockFields();
}
function showRecovered() {
  const recovered = readStorage(recoveredKey(activeCode));
  $('recovered-draft').hidden = !Array.isArray(recovered) || !recovered.length;
  $('recovered-draft-text').textContent = $('recovered-draft').hidden ? '' : recovered.map(draft => {
    const form = draft.form;
    return `${new Date(draft.savedAt).toLocaleString('pt-BR')} — rodada ${(form.votingRound ?? 0) + 1}\nProposta: ${form.proposalText || '(vazia)'}\nCrise: ${form.crisisTitle || ''}\nDetalhamento: ${form.crisisDetails || ''}\n${form.state.delegations.map(item => `${item.country}: ${VOTES[item.vote] || 'Sem voto'}${item.comment ? ` — ${item.comment}` : ''}`).join('\n')}`;
  }).join('\n\n');
}
function preserveConflict(form) {
  const previous = readStorage(recoveredKey(activeCode));
  const recovered = Array.isArray(previous) ? previous : [];
  recovered.push({ savedAt: new Date().toISOString(), form });
  writeStorage(recoveredKey(activeCode), recovered); showRecovered(); $('recovered-draft').open = true;
}
function reconcile(form, draft = read()) {
  autosave?.stop();
  preserveConflict(draft);
  submission = null; finalizing = false;
  acceptHistory(form); restore(form); writeStorage(draftKey(activeCode), null);
  startAutosave(); lockFields();
  votingMessage('Esta rodada foi concluída em outro formulário. O histórico foi atualizado e seu rascunho foi preservado abaixo.', 'error');
  status('Formulário atualizado para a rodada atual. Confira os dados antes de continuar.', 'saved');
}
function startAutosave() {
  const current = generation, code = activeCode;
  autosave = createAutosave(code, (state, error, saved) => {
    if (current !== generation) return;
    if (state === 'conflict') {
      if (saved) reconcile(saved);
      else { preserveConflict(read()); votingMessage('Não foi possível atualizar a rodada. Recarregue a página para recuperar o formulário atual.', 'error'); }
      return;
    }
    if (state === 'saved') {
      acceptHistory(saved);
      writeStorage(draftKey(code), null);
    }
    const labels = { pending: 'Alteração aguardando envio…', saving: 'Enviando ao painel geral…', saved: `${code}: alterações salvas e enviadas ao painel geral.`, error: `${error} Seus dados locais serão reenviados automaticamente.`, rejected: `${error} Corrija os dados para salvar novamente.` };
    status(labels[state] || error || '', state); lockFields();
    // The callback runs before the autosave promise clears its busy flag.
    if (state === 'saved') queueMicrotask(() => { if (current === generation) $('comite').disabled = loading || finalizing || Boolean(submission); });
  });
}
function finishSuccess(form, requestId) {
  autosave?.stop();
  acceptHistory(form);
  const proposal = proposals.find(item => item.id === requestId);
  submission = null; finalizing = false; restore(form); writeStorage(draftKey(activeCode), null);
  startAutosave(); lockFields();
  votingMessage(`Proposta ${proposal ? RESULTS[proposal.status].toLowerCase() : 'registrada'}. O registro está no histórico; escreva uma nova proposta para iniciar a próxima votação.`);
  status(`${activeCode}: votação registrada e enviada ao painel geral.`, 'saved');
}
async function open(code) {
  if (!committeeByCode(code)) return;
  const current = ++generation;
  loading = true; autosave?.stop(); stopWatch?.(); autosave = undefined;
  activeCode = code; lastRevision = -1; proposals = []; historyLoaded = false; submission = null; finalizing = false;
  restore(emptyForm(code)); renderHistory(); showRecovered(); votingMessage('');
  status(`Conectando ${code} ao acompanhamento geral…`);
  const url = new URL(location.href); url.searchParams.set('comite', code); history.replaceState(null, '', url);
  const stored = readStorage(draftKey(code));
  let cached = stored?.form || stored;
  if (cached?.committee !== code || !Array.isArray(cached?.state?.delegations)) cached = null;
  const waiting = stored?.submission?.requestId && stored?.submission?.form ? stored.submission : null;
  let server;
  try {
    server = await loadForm(code);
    if (current !== generation) return;
    acceptHistory(server); restore(server);
    if (waiting && proposals.some(item => item.id === waiting.requestId)) {
      writeStorage(draftKey(code), null); cached = null;
      votingMessage('A votação anterior já foi registrada. O histórico está atualizado.');
    } else if (cached && (cached.votingRound ?? 0) !== server.votingRound) {
      preserveConflict(cached); writeStorage(draftKey(code), null); cached = null;
      votingMessage('A rodada do rascunho já foi concluída. Seu texto foi preservado abaixo.', 'error');
    } else if (cached) {
      restore(cached); submission = waiting;
    }
    status(`${code}: formulário e histórico carregados.`, 'saved');
  } catch (error) {
    if (current !== generation) return;
    restore(cached || emptyForm(code)); submission = waiting;
    status(`${error.message} Alterações serão mantidas neste dispositivo.`, 'error');
  }
  if (current !== generation) return;
  loading = false; startAutosave(); lockFields();
  if (submission) votingMessage('A conclusão anterior ainda precisa ser confirmada. Clique em “Verificar e concluir votação”; o mesmo registro será usado, sem duplicar a proposta.', 'error');
  stopWatch = watchForm(code, update => {
    if (current !== generation || !update.state || update.revision < lastRevision) return;
    const newer = update.revision > lastRevision;
    acceptHistory(update);
    if (finalizing) return;
    if (submission) {
      if (proposals.some(item => item.id === submission.requestId)) finishSuccess(update, submission.requestId);
      else if (update.votingRound !== votingRound) reconcile(update, submission.form);
      return;
    }
    if (update.votingRound !== votingRound) {
      if (autosave.hasPending()) reconcile(update);
      else { restore(update); votingMessage('Uma votação foi concluída. O histórico e o formulário foram atualizados.'); }
      return;
    }
    if (newer && !autosave.hasPending()) restore(update);
  }, (state, error) => {
    if (current !== generation || autosave.hasPending() || finalizing || submission) return;
    if (state === 'connected') status(`${code} conectado. O painel geral acompanha este formulário.`, 'saved');
    if (state === 'error' || state === 'reconnecting') status(error || 'Sem conexão. Tentando reconectar…', 'error');
  });
  if (cached && !submission) { persist(); autosave(read()); }
}
function capture(event) {
  if (loading || finalizing || submission || !activeCode) return;
  if (!event.target.matches('.crise,.detalhamentocrise,.comentarios,#proposal-text,#votacao input')) return;
  const form = read(); persist(form); autosave?.(form); renderVote(); votingMessage('');
}
async function finishVoting() {
  if (!activeCode || loading || finalizing) return;
  if (!submission) {
    const form = read(), result = calculateVote(activeCode, form.state.delegations);
    if (!form.proposalText.trim() || result.counts.pending) { votingMessage('Escreva a proposta e registre o voto de todas as delegações.', 'error'); return; }
    submission = { requestId: crypto.randomUUID(), form };
    persist(form);
  }
  const current = generation, attempt = submission;
  finalizing = true; lockFields(); votingMessage('Registrando o resultado da proposta…');
  await autosave.stop();
  try {
    const saved = await finalizeProposal(activeCode, attempt.form, attempt.requestId);
    if (current === generation) finishSuccess(saved, attempt.requestId);
  } catch (error) {
    if (current !== generation) return;
    finalizing = false;
    if (error.status === 409 && error.snapshot) { reconcile(error.snapshot, attempt.form); return; }
    if (error.status >= 400 && error.status < 500 && error.status !== 408 && error.status !== 429) {
      submission = null; startAutosave(); persist(); lockFields();
      votingMessage(`${error.message} Corrija a proposta ou os votos e conclua novamente.`, 'error');
    } else {
      persist(attempt.form); lockFields();
      votingMessage(`${error.message} A conclusão ainda não foi confirmada. Use “Verificar e concluir votação” para tentar novamente sem duplicar o registro.`, 'error');
    }
  }
}
document.addEventListener('input', capture);
document.addEventListener('change', capture);
$('comite').addEventListener('change', () => open($('comite').value));
$('finish-voting').addEventListener('click', finishVoting);
window.addEventListener('beforeunload', event => { if (autosave?.hasPending() || submission) { event.preventDefault(); event.returnValue = ''; } });
document.querySelectorAll('#veto,#sem-veto,.paises-veto input').forEach(input => { input.disabled = true; });
const requested = new URL(location.href).searchParams.get('comite');
if (committeeByCode(requested)) await open(requested);

})();
