import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const read = file => readFile(join(root, file), 'utf8');
const output = join(root, 'codepen-updated');
await mkdir(output, { recursive: true });

// The CodePen JS panel needs one script rather than repository-relative imports.
const modules = ['config.js', 'committees.js', 'voting.js', 'client.js', 'live-integration.js'];
const inline = source => source
  .replace(/^import .*;\r?\n/gm, '')
  .replace(/^export \{[^}]*\};\r?\n/gm, '')
  .replace(/^export /gm, '');
const classic = await read('script.js');
const javascript = `// Generated by npm run build:codepen. Configure API_BASE below before using the backend.\n(async () => {\n${classic}\nwindow.selecao = selecao;\n${(await Promise.all(modules.map(read))).map(inline).join('\n')}\n})();\n`;
const html = (await read('index.html')).match(/<body>([\s\S]*?)<\/body>/i)[1]
  .replace(/\s*<script\b[^>]*>[\s\S]*?<\/script>/gi, '')
  .replace('href="supervisor.html"', 'href="https://galaobiel4.github.io/mun-system/supervisor.html"')
  .trim() + '\n';
const css = `${await read('style.css')}\n${await read('live.css')}\n`;
await writeFile(join(output, 'index.html'), html);
await writeFile(join(output, 'script.js'), javascript);
await writeFile(join(output, 'style.css'), css);
console.log('Updated CodePen HTML, CSS, and JavaScript written to codepen-updated/.');
